# Generated by Django 5.2.7 on 2025-11-11 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('fecha_contratacion', models.DateField()),
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('cargo', models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('ALMACEN', 'Almacen'), ('CAJERO', 'Cajero')], max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('num_sucursal', models.IntegerField()),
                ('encargado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=50)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='app_muebleria.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('SALA', 'Sala'), ('COMEDOR', 'Comedor'), ('RECAMARA', 'Recámara'), ('OFICINA', 'Oficina')], max_length=20)),
                ('material', models.CharField(choices=[('MADERA', 'Madera'), ('METAL', 'Metal'), ('PLASTICO', 'Plástico'), ('VIDRIO', 'Vidrio')], max_length=20)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('sucursales', models.ManyToManyField(related_name='productos', to='app_muebleria.sucursal')),
            ],
        ),
    ]
